### ISSUE TITLE
Uploading deck on Ankidroid crashes Ankidroid. 

### ISSUE THREAD

**Issue by dummifiedme** [alemayhu/Notion-to-Anki#213]
The export just had a few sample questions.
 
I was trying to check for the hierarchical tags issue here. To see if it works.

But accidentally found out that, uploading any deck created by 2anki.net, isn't getting added to AnkiDroid, instead it crashes AnkiDroid.

I don't yet know if it's an AnkiDroid issue or 2anki Issue.

**Comment by aalemayhu** [comment]
Hei @dummifiedme 

I really don't know what you are talking about. Please be more specific or elaborate. If you can explain what you were trying and what happened instead. That would be good. Also screenshots help.

Thanks!

**Comment by dummifiedme** [comment]
> Hei @dummifiedme 
> 
> 
> 
> I really don't know what you are talking about. Please be more specific or elaborate. If you can explain what you were trying and what happened instead. That would be good. Also screenshots help.
> 
> 
> 
> Thanks!

I trekked elaborating the issue. (Edited the original comment).
I just meant to say, the apkg created from notion2anki crashes the AnkiDroid upon trying to import.

**Comment by aalemayhu** [comment]
Hei @dummifiedme. I asked Abi to reproduce this. He could not. Can you share more information about Android device and version? Thanks!

**Comment by dummifiedme** [comment]
@aalemayhu, I am sorry I couldn't respond. I will try again once I get hold of my Android device. It will take some time :)

**Comment by aalemayhu** [comment]
Sure, if you can share the page you used, that would be great! This way others can help out with the testing.

**Comment by chan18** [comment]
I will try to fix this @aalemayhu .

**Comment by aalemayhu** [comment]
I just tried this two times now, it works fine on Android.

**Comment by aalemayhu** [comment]
Second-pass review (engineer): Relevant code exists but no fix commit found

Evidence: code in: web/src/pages/LandingPage/copy/pdf.ts
node_modules/.pnpm/@aws-sdk+client-s3@3.10

**Comment by aalemayhu** [comment]
**Verification pass (2026-05-31)** — confirmed still reproducible in principle, but root cause is **undiagnosed**; this needs a real repro before any fix.

**Status:** STILL_LIVE (medium confidence). No fix commit was ever found for this.

**Two suspected causes (need to confirm which):**
1. The custom 3-field note types (`Front` / `Back` / `MyMedia`) are incompatible with AnkiDroid — `src/templates/n2a-basic.json` and `src/templates/n2a-cloze.json` both declare a 3-field structure.
2. The `MyMedia` field handling in `.apkg` generation is malformed for AnkiDroid — populated with comma-separated filenames in `create_deck/create_deck.py`, packaged via `create_deck/helpers/write_apkg.py`.

**Next step (gate before coding):** reproduce on a real AnkiDroid client. Generate a deck from 2anki, import it into current AnkiDroid, and capture the crash. Until the failure mode is observed, a fix would be a guess — possible directions are (a) reduce the note type to 2 fields with media handled in a hidden field, or (b) verify `_write_new_apkg` assigns media to the genanki `Package` correctly. Decide A vs B from the actual crash, not from the templates alone.

Holding off on a blind fix per the repo's "no false fix artifacts" rule.

**Comment by aalemayhu** [comment]
Closing pending a fresh reproduction. This was reported once in 2020 and never reproduced — two of us tried on Android at the time and the import worked, and no device/OS version or sample deck was available to chase it. Six years and many AnkiDroid releases later, 2anki decks import on Android routinely, so there's no evidence of a structural `.apkg` defect.

This isn't a "won't fix" — if anyone hits an AnkiDroid import crash on a current build, please open a new issue with the Android + AnkiDroid version and a deck that reproduces it, and we'll act on it immediately. A concrete repro is the one thing that was missing.
